from ibm_watsonx_ai.foundation_models import ModelInference
from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams
from ibm_watsonx_ai.metanames import EmbedTextParamsMetaNames
from ibm_watsonx_ai import Credentials
from langchain_ibm import WatsonxLLM, WatsonxEmbeddings
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_community.document_loaders import PyPDFLoader
from langchain.chains import RetrievalQA
from dotenv import load_dotenv
import os

import gradio as gr
load_dotenv()
# You can use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

## > Initialize the LLM
def get_llm():
    model_id = 'mistralai/mistral-medium-2505'
    parameters = {
        GenParams.MAX_NEW_TOKENS: 256,
        GenParams.TEMPERATURE: 0.5,
    }
    watsonx_llm = WatsonxLLM(
        model_id=model_id,
        url= "https://jp-tok.ml.cloud.ibm.com",
        project_id= os.getenv("PROJECT_ID"),
        params=parameters,
        apikey= os.getenv("API_KEY")
    )
    return watsonx_llm

## > Document loader
def document_loader(file):
    loader = PyPDFLoader(file.name)
    loaded_document = loader.load()
    return loaded_document

## > Text Splitter
def text_splitter(data):
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=50,
        length_function=len,
    )
    chunks = text_splitter.split_documents(data)
    return chunks

## > Vector Store
def vertor_database(chunks):
    embedding_model = watsonx_embedding()
    vectordb = Chroma.from_documents(chunks, embedding_model)
    return vectordb

## > Embedding model
def watsonx_embedding():
    embed_params = {
        EmbedTextParamsMetaNames.TRUNCATE_INPUT_TOKENS: 3,
        EmbedTextParamsMetaNames.RETURN_OPTIONS: {"input_text": True},
    }
    WatsonxEmbeddings(
        model_id="ibm/slate-125m-english-rtrvr-v2",
        url= "https://jp-tok.ml.cloud.ibm.com",
        project_id= os.getenv("PROJECT_ID"),
        params=embed_params,
        apikey= os.getenv("API_KEY")
    )
    return watsonx_embedding

## > Define the retriver
def retriever(file):
    document = document_loader(file)
    chunks = text_splitter(document)
    vectordb = vertor_database(chunks)
    retriever = vectordb.as_restriever()
    return retriever

print("-- End --")